platformName=Android
automationName=UiAutomator2
deviceName=emulator-5554
udid=emulator-5554

appiumServerURL=http://127.0.0.1:4723

app=apps/RecipeFind_Debug_v4.0.1.apk

newCommandTimeout=300

gmail.email=testuser124355@gmail.com
gmail.password=TestCase@123

superadmin.email=mohit.aman1998@gmail.com
superadmin.password=x5V8pM6c9NsBQiP3bNeiig==

groupadmin.email=testuser124355@gmail.com
groupadmin.password=TestCase@123

normaluser.email=mohit.aman05111998@gmail.com
normaluser.password=zebronicSmi7@11

reviewer.email=ssstesting9@gmail.com
reviewer.password=Sonam@123