platformName=Android
automationName=UiAutomator2
deviceName=emulator-5554
udid=emulator-5554

appiumServerURL=http://127.0.0.1:4723

app=apps/RecipeFInd_Debug_v3.0.6.apk

newCommandTimeout=300

gmail.email=testuser124355@gmail.com
gmail.password=TestCase@1234